import type { Ability } from '@/types';

export const DEFAULT_ABILITIES: Ability[] = [
    // === HACKING ABILITIES ===
    {
        id: 'hack_01',
        name: 'PACKET SNIFFER',
        category: 'UTILITY',
        description: 'Intercept and decode nearby data transmissions.',
        levelRequired: 1,
        cooldown: 'None',
        cost: 'Passive',
        effect: '+10% chance to discover hidden quest data in sector scans.',
        unlocked: true,
    },
    {
        id: 'hack_02',
        name: 'BRUTE FORCE',
        category: 'OFFENSIVE',
        description: 'Overwhelm a target system with raw computational power.',
        levelRequired: 5,
        cooldown: '3 rounds',
        cost: '15 energy',
        effect: 'Deal 20 digital damage. +30% if target HACKING < yours.',
        unlocked: false,
    },
    {
        id: 'hack_03',
        name: 'FIREWALL',
        category: 'DEFENSIVE',
        description: 'Erect a protective barrier of encrypted protocols.',
        levelRequired: 10,
        cooldown: '5 rounds',
        cost: '20 energy',
        effect: 'Block next 2 incoming digital attacks.',
        unlocked: false,
    },
    {
        id: 'hack_04',
        name: 'ZERO-DAY EXPLOIT',
        category: 'OFFENSIVE',
        description: 'Deploy an unknown vulnerability against any system.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: '50 energy',
        effect: 'Guaranteed critical hit. Ignores all defenses.',
        unlocked: false,
    },

    // === COMBAT ABILITIES ===
    {
        id: 'combat_01',
        name: 'BLADE RUSH',
        category: 'OFFENSIVE',
        description: 'Close the gap in an instant with a devastating melee strike.',
        levelRequired: 1,
        cooldown: 'None',
        cost: '10 energy',
        effect: 'Deal 15 physical damage. Ignores target positioning.',
        unlocked: true,
    },
    {
        id: 'combat_02',
        name: 'IRON GUARD',
        category: 'DEFENSIVE',
        description: 'Assume a fortified stance, absorbing incoming damage.',
        levelRequired: 5,
        cooldown: '4 rounds',
        cost: '15 energy',
        effect: 'Reduce all incoming damage by 50% for 2 rounds.',
        unlocked: false,
    },
    {
        id: 'combat_03',
        name: 'BERSERKER RAGE',
        category: 'OFFENSIVE',
        description: 'Enter a frenzied state of heightened aggression.',
        levelRequired: 10,
        cooldown: '6 rounds',
        cost: '25 energy',
        effect: 'Double damage output for 3 rounds. Defense reduced by 30%.',
        unlocked: false,
    },
    {
        id: 'combat_04',
        name: 'DEATHSTROKE',
        category: 'OFFENSIVE',
        description: 'Channel all remaining power into a single devastating blow.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: '60 energy',
        effect: 'Deal 100 damage. If target HP < 25%, instant elimination.',
        unlocked: false,
    },

    // === DIPLOMACY ABILITIES ===
    {
        id: 'diplo_01',
        name: 'SILVER TONGUE',
        category: 'UTILITY',
        description: 'Speak with persuasive eloquence that sways even hostile NPCs.',
        levelRequired: 1,
        cooldown: 'None',
        cost: 'Passive',
        effect: '+15% success rate on all negotiation and persuasion checks.',
        unlocked: true,
    },
    {
        id: 'diplo_02',
        name: 'CEASEFIRE',
        category: 'DEFENSIVE',
        description: 'Halt all hostilities in the immediate area temporarily.',
        levelRequired: 5,
        cooldown: '5 rounds',
        cost: '20 energy',
        effect: 'Prevent all combatants from attacking for 2 rounds.',
        unlocked: false,
    },
    {
        id: 'diplo_03',
        name: 'ALLIANCE PACT',
        category: 'UTILITY',
        description: 'Forge a temporary alliance with a neutral or enemy faction.',
        levelRequired: 10,
        cooldown: '1 per session',
        cost: '30 energy',
        effect: 'Gain faction reinforcements for the current encounter.',
        unlocked: false,
    },
    {
        id: 'diplo_04',
        name: 'SOVEREIGN DECREE',
        category: 'UTILITY',
        description: 'Issue an unquestionable mandate that reshapes local politics.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: '50 energy',
        effect: 'Force any NPC to comply with a single command. Cannot cause self-harm.',
        unlocked: false,
    },

    // === SURVIVAL ABILITIES ===
    {
        id: 'surv_01',
        name: 'FIELD MEDIC',
        category: 'UTILITY',
        description: 'Administer emergency medical treatment with salvaged supplies.',
        levelRequired: 1,
        cooldown: '3 rounds',
        cost: '10 energy',
        effect: 'Restore 25 HP to self or ally.',
        unlocked: true,
    },
    {
        id: 'surv_02',
        name: 'SCAVENGER',
        category: 'PASSIVE',
        description: 'Extract usable resources from any environment.',
        levelRequired: 5,
        cooldown: 'None',
        cost: 'Passive',
        effect: '+20% loot quality from all sources. Find items others miss.',
        unlocked: false,
    },
    {
        id: 'surv_03',
        name: 'DEAD RECKONING',
        category: 'UTILITY',
        description: 'Navigate unerringly through hazardous and uncharted terrain.',
        levelRequired: 10,
        cooldown: 'None',
        cost: 'Passive',
        effect: 'Ignore environmental hazards. Reveal hidden paths in all sectors.',
        unlocked: false,
    },
    {
        id: 'surv_04',
        name: 'LAST STAND',
        category: 'DEFENSIVE',
        description: 'When all hope is lost, refuse to fall.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: 'Triggered',
        effect: 'Upon fatal damage, survive with 1 HP and gain immunity for 1 round.',
        unlocked: false,
    },

    // === ARCANA ABILITIES ===
    {
        id: 'arcana_01',
        name: 'MINOR WARD',
        category: 'DEFENSIVE',
        description: 'Weave a shimmering barrier of arcane energy.',
        levelRequired: 1,
        cooldown: '2 rounds',
        cost: '10 mana',
        effect: 'Absorb up to 20 damage from the next incoming attack.',
        unlocked: true,
    },
    {
        id: 'arcana_02',
        name: 'RIFT SENSE',
        category: 'UTILITY',
        description: 'Attune to the fabric of reality, detecting anomalies nearby.',
        levelRequired: 5,
        cooldown: 'None',
        cost: 'Passive',
        effect: 'Automatically detect glitches and anomaly events within 2 sectors.',
        unlocked: false,
    },
    {
        id: 'arcana_03',
        name: 'ARCANE BLAST',
        category: 'OFFENSIVE',
        description: 'Unleash a concentrated beam of pure arcane force.',
        levelRequired: 10,
        cooldown: '4 rounds',
        cost: '30 mana',
        effect: 'Deal 40 arcane damage. Pierces physical defenses.',
        unlocked: false,
    },
    {
        id: 'arcana_04',
        name: 'DIMENSIONAL TEAR',
        category: 'OFFENSIVE',
        description: 'Rip a hole in the fabric between dimensions.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: '70 mana',
        effect: 'Deal 80 void damage in an area. 20% chance to banish target.',
        unlocked: false,
    },

    // === ENGINEERING ABILITIES ===
    {
        id: 'eng_01',
        name: 'FIELD REPAIR',
        category: 'UTILITY',
        description: 'Jury-rig broken equipment back to operational status.',
        levelRequired: 1,
        cooldown: '3 rounds',
        cost: '10 energy',
        effect: 'Restore 1 equipment durability. Remove malfunction debuffs.',
        unlocked: true,
    },
    {
        id: 'eng_02',
        name: 'TURRET DEPLOY',
        category: 'OFFENSIVE',
        description: 'Assemble and deploy an automated sentry turret.',
        levelRequired: 5,
        cooldown: '6 rounds',
        cost: '25 energy',
        effect: 'Place a turret that deals 10 damage per round for 4 rounds.',
        unlocked: false,
    },
    {
        id: 'eng_03',
        name: 'OVERCLOCK',
        category: 'UTILITY',
        description: 'Push equipment beyond its rated limits.',
        levelRequired: 10,
        cooldown: '5 rounds',
        cost: '20 energy',
        effect: 'Double all equipment stat bonuses for 3 rounds. Risk of malfunction.',
        unlocked: false,
    },
    {
        id: 'eng_04',
        name: 'MECH SUMMON',
        category: 'OFFENSIVE',
        description: 'Call in a combat automaton from your personal workshop.',
        levelRequired: 20,
        cooldown: '1 per day',
        cost: '60 energy',
        effect: 'Summon a mech ally with 100 HP and 25 damage per round for 5 rounds.',
        unlocked: false,
    },
];
