import type { Sector } from '@/types';

export const SECTORS: Sector[] = [
    // ════════════════════════════════════════
    // SECTORS 1-10: URBAN / CYBERPUNK (TECHNOCRAT TERRITORY)
    // ════════════════════════════════════════
    {
        id: 1, name: 'Neon Abyss', controlledBy: 'TECHNOCRATS', threatLevel: 2,
        activeEvents: [], terrain: 'urban', weather: 'rain',
        description: 'A sunken district of perpetual neon glow. Data brokers and rogue AIs trade secrets beneath flickering holograms. The rain never stops here.',
        resources: ['Data Fragments', 'Circuit Boards'],
        npcsPresent: ['CIPHER_ZERO'],
        discovered: true, adjacentSectors: [2, 3, 6, 11],
        pointsOfInterest: [
            { id: 'poi_1_1', name: 'The Byte Bazaar', type: 'vendor', discovered: true, description: 'A sprawling underground market where data is the only currency.' },
            { id: 'poi_1_2', name: 'Signal Tower Alpha', type: 'landmark', discovered: false, description: 'The first transmission tower ever built on The Grid. Still operational.' },
        ],
    },
    {
        id: 2, name: 'Rift of Echoes', controlledBy: 'TECHNOCRATS', threatLevel: 3,
        activeEvents: [], terrain: 'urban', weather: 'fog',
        description: 'A corridor of abandoned server halls where old data echoes off crystallized walls. Fragments of dead programs whisper through the static.',
        resources: ['Echo Crystals', 'Corrupted Data'],
        npcsPresent: ['GHOST_SIGNAL'],
        discovered: false, adjacentSectors: [1, 3, 4, 7],
        pointsOfInterest: [
            { id: 'poi_2_1', name: 'Archive Vault 7', type: 'dungeon', discovered: false, description: 'A sealed data vault containing pre-Construct records. Heavily defended by rogue firewalls.' },
            { id: 'poi_2_2', name: 'The Whispering Wall', type: 'anomaly', discovered: false, description: 'A crystalline surface that plays back transmissions from other timelines.' },
        ],
    },
    {
        id: 3, name: 'Iron Citadel', controlledBy: 'TECHNOCRATS', threatLevel: 4,
        activeEvents: [], terrain: 'urban', weather: 'clear',
        description: 'The primary Technocrat stronghold. Massive data spires pierce the sky, their surfaces alive with crawling code. Security is absolute.',
        resources: ['Refined Alloy', 'Quantum Keys'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [1, 2, 4, 5, 8],
        pointsOfInterest: [
            { id: 'poi_3_1', name: 'Central Processing Tower', type: 'landmark', discovered: false, description: 'The beating heart of Technocrat operations. All Grid data flows through here.' },
            { id: 'poi_3_2', name: 'The Calibration Chamber', type: 'dungeon', discovered: false, description: 'A training facility where Architects are tested. Few pass.' },
            { id: 'poi_3_3', name: "Engineer's Workshop", type: 'vendor', discovered: false, description: 'Custom implants and upgrades. Prices are steep but the quality is unmatched.' },
        ],
    },
    {
        id: 4, name: 'Chrono Wastes', controlledBy: 'TECHNOCRATS', threatLevel: 5,
        activeEvents: [], terrain: 'wasteland', weather: 'anomaly',
        description: 'Time flows inconsistently here. Clocks run backward, then forward, then stop. Temporal anomalies have left this sector in a state of permanent déjà vu.',
        resources: ['Temporal Shards', 'Chrono Dust'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [2, 3, 5, 9],
        pointsOfInterest: [
            { id: 'poi_4_1', name: 'The Frozen Moment', type: 'anomaly', discovered: false, description: 'A pocket of frozen time containing a scene from before The Construct. Researchers study it endlessly.' },
            { id: 'poi_4_2', name: 'Paradox Beacon', type: 'landmark', discovered: false, description: 'A device that broadcasts the same signal on a loop. No one knows who built it or why.' },
        ],
    },
    {
        id: 5, name: 'The Silicon Expanse', controlledBy: 'TECHNOCRATS', threatLevel: 3,
        activeEvents: [], terrain: 'urban', weather: 'clear',
        description: 'Vast plains of silicon crystal stretching to the horizon. Automated factories process raw data into usable components. The hum of industry is deafening.',
        resources: ['Raw Silicon', 'Processing Chips', 'Scrap Metal'],
        npcsPresent: ['NULL_BYTE'],
        discovered: false, adjacentSectors: [3, 4, 6, 10],
        pointsOfInterest: [
            { id: 'poi_5_1', name: 'Factory Floor 9', type: 'dungeon', discovered: false, description: 'An automated factory gone rogue. Its machines build things no one ordered.' },
            { id: 'poi_5_2', name: 'Silicon Market', type: 'vendor', discovered: false, description: 'Bulk materials at wholesale prices. If you know the right access codes.' },
        ],
    },
    {
        id: 6, name: 'Null Sector', controlledBy: 'TECHNOCRATS', threatLevel: 6,
        activeEvents: [], terrain: 'void', weather: 'anomaly',
        description: 'A region where The Grid itself is absent. Nothing renders here. Architects who enter describe a void of absolute silence and formless potential.',
        resources: ['Void Essence', 'Null Fragments'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [1, 5, 7, 31],
        pointsOfInterest: [
            { id: 'poi_6_1', name: 'The Empty Throne', type: 'anomaly', discovered: false, description: 'A structure that exists only when observed. Turn away and it vanishes.' },
        ],
    },
    {
        id: 7, name: 'Aether Node', controlledBy: 'TECHNOCRATS', threatLevel: 3,
        activeEvents: [], terrain: 'urban', weather: 'clear',
        description: 'A massive junction where data streams converge from across The Grid. Information flows like rivers of light through transparent conduits.',
        resources: ['Data Fragments', 'Aether Crystals'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [2, 6, 8, 12],
        pointsOfInterest: [
            { id: 'poi_7_1', name: 'Stream Confluence', type: 'landmark', discovered: false, description: 'Where three data rivers meet. The patterns they form are mesmerizing and possibly prophetic.' },
            { id: 'poi_7_2', name: "Data Fisher's Dock", type: 'vendor', discovered: false, description: 'An eccentric vendor who "fishes" for rare data in the streams.' },
        ],
    },
    {
        id: 8, name: 'Crimson Spire', controlledBy: 'TECHNOCRATS', threatLevel: 5,
        activeEvents: [], terrain: 'urban', weather: 'storm',
        description: 'A towering red monolith crackling with energy. Lightning strikes its peak every few seconds, powering unknown systems deep within.',
        resources: ['Storm Cells', 'Red Crystal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [3, 7, 9, 13],
        pointsOfInterest: [
            { id: 'poi_8_1', name: 'The Spire Interior', type: 'dungeon', discovered: false, description: 'Floors of increasingly dangerous defense systems. Whatever is at the top, someone wants it guarded.' },
            { id: 'poi_8_2', name: 'Lightning Rod Café', type: 'settlement', discovered: false, description: 'A small community of storm chasers who live in the Spires shadow.' },
        ],
    },
    {
        id: 9, name: 'Obsidian Core', controlledBy: 'TECHNOCRATS', threatLevel: 7,
        activeEvents: [], terrain: 'underground', weather: 'clear',
        description: 'Deep beneath The Grid lies a sphere of black glass containing the original source code. Access is forbidden. Security is lethal.',
        resources: ['Obsidian Shards', 'Source Fragments'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [4, 8, 10, 14],
        pointsOfInterest: [
            { id: 'poi_9_1', name: 'The Source Chamber', type: 'dungeon', discovered: false, description: 'Legend says the original Construct code lives here. No one who has entered has returned to confirm.' },
        ],
    },
    {
        id: 10, name: 'The Fractal Weave', controlledBy: 'TECHNOCRATS', threatLevel: 4,
        activeEvents: [], terrain: 'urban', weather: 'clear',
        description: 'A district where architecture follows fractal mathematics. Buildings repeat at every scale. Getting lost is inevitable; some say intentional.',
        resources: ['Fractal Keys', 'Geometric Alloy'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [5, 9, 15, 31],
        pointsOfInterest: [
            { id: 'poi_10_1', name: 'Mandelbrot Square', type: 'landmark', discovered: false, description: 'The central plaza. Its shape is the same whether viewed from orbit or from a centimeter away.' },
            { id: 'poi_10_2', name: 'The Recursive Shop', type: 'vendor', discovered: false, description: 'A vendor who sells copies of copies. The quality degrades with each iteration. Or does it?' },
        ],
    },

    // ════════════════════════════════════════
    // SECTORS 11-20: MYSTICAL / FOREST / VOID (KEEPER TERRITORY)
    // ════════════════════════════════════════
    {
        id: 11, name: 'Zenith Station', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 2,
        activeEvents: [], terrain: 'forest', weather: 'fog',
        description: 'An ancient station overgrown with luminescent vines. The Keepers maintain it as a waypoint between the physical and spectral layers of The Grid.',
        resources: ['Luminous Spores', 'Ancient Wood'],
        npcsPresent: ['VEIL_WALKER'],
        discovered: false, adjacentSectors: [1, 12, 16, 32],
        pointsOfInterest: [
            { id: 'poi_11_1', name: 'The Veil Gate', type: 'landmark', discovered: false, description: 'A shimmering portal to the spectral layer. Only Keepers know the words to open it.' },
            { id: 'poi_11_2', name: "Herbalist's Hollow", type: 'vendor', discovered: false, description: 'Potions, salves, and enchanted circuit-fungi. Organic computing at its finest.' },
        ],
    },
    {
        id: 12, name: 'Void Shallows', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 4,
        activeEvents: [], terrain: 'void', weather: 'fog',
        description: 'Where The Grid thins to almost nothing. Reality here is ankle-deep — you can see the raw code beneath your feet like water over sand.',
        resources: ['Void Thread', 'Thin-Space Crystals'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [7, 11, 13, 17],
        pointsOfInterest: [
            { id: 'poi_12_1', name: 'The Shore of Nothing', type: 'anomaly', discovered: false, description: 'The exact boundary where rendered reality ends. Step beyond and you cease to render.' },
        ],
    },
    {
        id: 13, name: 'Quantum Trench', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 5,
        activeEvents: [], terrain: 'aquatic', weather: 'storm',
        description: 'A deep fissure filled with liquid data. Massive constructs swim in its depths — ancient programs too large to run anywhere else.',
        resources: ['Deep Data', 'Quantum Pearls'],
        npcsPresent: ['SHADOW_LOOM'],
        discovered: false, adjacentSectors: [8, 12, 14, 18],
        pointsOfInterest: [
            { id: 'poi_13_1', name: 'The Leviathan\'s Lair', type: 'dungeon', discovered: false, description: 'Home to a colossal legacy program. It does not appreciate visitors.' },
            { id: 'poi_13_2', name: 'Pearl Driver\'s Dock', type: 'vendor', discovered: false, description: 'Divers harvest Quantum Pearls from the trench floor. Dangerous but lucrative trade.' },
        ],
    },
    {
        id: 14, name: 'Aurora Belt', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 3,
        activeEvents: [], terrain: 'forest', weather: 'clear',
        description: 'Bands of colored light arc across the sky like frozen lightning. The forest below glows in sympathy. Peace permeates every pixel.',
        resources: ['Aurora Dust', 'Spectral Wood'],
        npcsPresent: ['EMBER_WITCH'],
        discovered: false, adjacentSectors: [9, 13, 15, 19],
        pointsOfInterest: [
            { id: 'poi_14_1', name: 'The Color Garden', type: 'landmark', discovered: false, description: 'A grove where every tree produces a different color of light. Meditative and beautiful.' },
            { id: 'poi_14_2', name: 'Aurora Sanctuary', type: 'settlement', discovered: false, description: 'A peaceful commune of Keeper monks who study the aurora patterns for prophecy.' },
        ],
    },
    {
        id: 15, name: 'Rust Valley', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 4,
        activeEvents: [], terrain: 'ruins', weather: 'rain',
        description: 'An ancient industrial zone reclaimed by nature. Rusted machinery pokes through moss and vine. The Keepers see poetry in the decay.',
        resources: ['Rusted Relics', 'Reclaimed Metal', 'Wild Data'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [10, 14, 16, 20],
        pointsOfInterest: [
            { id: 'poi_15_1', name: 'The Overgrown Foundry', type: 'dungeon', discovered: false, description: 'Once a great forge. Now a labyrinth of roots and corroded steel. Something still beats in its furnace.' },
            { id: 'poi_15_2', name: "Scavenger's Rest", type: 'settlement', discovered: false, description: 'A village built from salvaged machinery. The residents are wary but fair.' },
        ],
    },
    {
        id: 16, name: 'Echo Terminal', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 3,
        activeEvents: [], terrain: 'forest', weather: 'clear',
        description: 'A terminal hub wrapped in ancient trees. Every sound repeats three times with increasing distortion. The Keepers use it for long-range communication.',
        resources: ['Resonance Shards', 'Living Wire'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [11, 15, 17, 33],
        pointsOfInterest: [
            { id: 'poi_16_1', name: 'The Resonance Chamber', type: 'landmark', discovered: false, description: 'Speak here and your words reach across three sectors. Volume does not help.' },
        ],
    },
    {
        id: 17, name: 'Shadow Nexus', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 6,
        activeEvents: [], terrain: 'void', weather: 'fog',
        description: 'The intersection of all shadows. Light cannot persist here — it is consumed on entry. The Keepers navigate by touch and whisper.',
        resources: ['Shadow Silk', 'Dark Matter'],
        npcsPresent: ['SHADOW_LOOM'],
        discovered: false, adjacentSectors: [12, 16, 18, 34],
        pointsOfInterest: [
            { id: 'poi_17_1', name: 'The Loom', type: 'anomaly', discovered: false, description: 'A structure that weaves shadows into physical forms. Used by SHADOW_LOOM for unknown purposes.' },
            { id: 'poi_17_2', name: 'Blindfold Market', type: 'vendor', discovered: false, description: 'A market where all transactions occur in total darkness. Honesty is enforced by tradition.' },
        ],
    },
    {
        id: 18, name: 'Crystal Dunes', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 4,
        activeEvents: [], terrain: 'wasteland', weather: 'sandstorm',
        description: 'Desert of crystallized data. Each grain is a compressed memory. Sandstorms here do not abrade — they overwrite.',
        resources: ['Memory Crystal', 'Sand Glass'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [13, 17, 19, 35],
        pointsOfInterest: [
            { id: 'poi_18_1', name: 'The Memory Palace', type: 'dungeon', discovered: false, description: 'A structure that forms and dissolves with the dunes. Its rooms are made of compressed memories.' },
            { id: 'poi_18_2', name: 'Dune Oracle', type: 'anomaly', discovered: false, description: 'A formation that reshapes to answer questions. Its answers are cryptic but accurate.' },
        ],
    },
    {
        id: 19, name: 'The Ashen Peaks', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 5,
        activeEvents: [], terrain: 'mountain', weather: 'clear',
        description: 'Mountains of gray ash, remnants of a computational fire long extinct. The peaks still glow faintly at night. The Keepers revere them as sacred.',
        resources: ['Sacred Ash', 'Ember Stones'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [14, 18, 20, 36],
        pointsOfInterest: [
            { id: 'poi_19_1', name: 'The Summit Shrine', type: 'landmark', discovered: false, description: 'A Keeper shrine at the highest peak. The view encompasses seven sectors.' },
            { id: 'poi_19_2', name: 'The Ashen Caves', type: 'dungeon', discovered: false, description: 'Tunnels through the ash mountains. Something ancient stirs in the deepest chambers.' },
        ],
    },
    {
        id: 20, name: 'Cybernetic Ring', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 3,
        activeEvents: [], terrain: 'forest', weather: 'rain',
        description: 'A perfect circle of hybrid trees — half organic, half machine. The boundary between Keeper mysticism and Technocrat engineering blurs here.',
        resources: ['Hybrid Bark', 'Bio-Circuit'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [15, 19, 21, 37],
        pointsOfInterest: [
            { id: 'poi_20_1', name: 'The Synthesis Tree', type: 'landmark', discovered: false, description: 'The oldest hybrid tree. Its roots run under three sectors. Its canopy generates its own weather.' },
        ],
    },

    // ════════════════════════════════════════
    // SECTORS 21-30: WASTELAND / MOUNTAIN / RUINS (IRONBORN TERRITORY)
    // ════════════════════════════════════════
    {
        id: 21, name: 'Ghost Matrix', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 4,
        activeEvents: [], terrain: 'ruins', weather: 'fog',
        description: 'The skeletal remains of an ancient computational network. Hollow towers of rusted steel stand like tombstones. The Ironborn mine them for metal.',
        resources: ['Scrap Metal', 'Ghost Wire'],
        npcsPresent: ['IRON_HAND'],
        discovered: false, adjacentSectors: [20, 22, 26, 38],
        pointsOfInterest: [
            { id: 'poi_21_1', name: 'The Scrap Pits', type: 'dungeon', discovered: false, description: 'Deep excavations where the Ironborn extract rare metals. Structural collapse is a constant risk.' },
            { id: 'poi_21_2', name: "Ironmonger's Forge", type: 'vendor', discovered: false, description: 'The finest blacksmith on The Grid. Will craft anything if you bring the materials.' },
        ],
    },
    {
        id: 22, name: 'Lumina Sector', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 3,
        activeEvents: [], terrain: 'wasteland', weather: 'clear',
        description: 'A barren plain lit by bioluminescent minerals embedded in the ground. The Ironborn have built fortifications across the glowing landscape.',
        resources: ['Lumina Ore', 'Glowing Resin'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [21, 23, 27],
        pointsOfInterest: [
            { id: 'poi_22_1', name: 'Fort Lumina', type: 'settlement', discovered: false, description: 'An Ironborn stronghold. Its walls glow with embedded minerals, making night attacks impossible.' },
        ],
    },
    {
        id: 23, name: 'The Dark Bastion', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 6,
        activeEvents: [], terrain: 'mountain', weather: 'storm',
        description: 'A fortress carved from black stone on a storm-wracked peak. The Ironborn command center. Lightning illuminates its brutal architecture.',
        resources: ['Dark Stone', 'Storm Iron'],
        npcsPresent: ['RUST_PROPHET'],
        discovered: false, adjacentSectors: [22, 24, 28],
        pointsOfInterest: [
            { id: 'poi_23_1', name: 'The War Room', type: 'landmark', discovered: false, description: 'Where Ironborn strategy is forged. Maps of every sector cover the walls.' },
            { id: 'poi_23_2', name: 'The Proving Grounds', type: 'dungeon', discovered: false, description: 'An arena where Ironborn warriors test their mettle. Only the strongest earn the right to lead.' },
        ],
    },
    {
        id: 24, name: 'Silver Circuit', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 4,
        activeEvents: [], terrain: 'wasteland', weather: 'clear',
        description: 'A loop of silver-threaded terrain where old power conduits still hum. The Ironborn tap these lines for energy to fuel their forges.',
        resources: ['Silver Thread', 'Power Cells'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [23, 25, 29],
        pointsOfInterest: [
            { id: 'poi_24_1', name: 'Power Station Omega', type: 'landmark', discovered: false, description: 'A still-functional power station. Its output could power a small city.' },
            { id: 'poi_24_2', name: 'Circuit Trader', type: 'vendor', discovered: false, description: 'Deals in power cells and energy equipment. Fair prices for Ironborn, steep for outsiders.' },
        ],
    },
    {
        id: 25, name: 'Temporal Rift', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 7,
        activeEvents: [], terrain: 'void', weather: 'anomaly',
        description: 'A tear in The Grid where time and space are unreliable. The Ironborn have built stabilizers around the rift to harvest its energy.',
        resources: ['Temporal Shards', 'Rift Metal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [24, 26, 30],
        pointsOfInterest: [
            { id: 'poi_25_1', name: 'The Rift Core', type: 'anomaly', discovered: false, description: 'The center of the temporal distortion. Time flows backward near its edge.' },
        ],
    },
    {
        id: 26, name: 'The Shattered Moon', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 5,
        activeEvents: [], terrain: 'ruins', weather: 'clear',
        description: 'Fragments of a celestial construct litter the landscape. Each shard contains partial datasets of something vast and ancient.',
        resources: ['Moon Fragments', 'Celestial Data'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [21, 25, 27, 39],
        pointsOfInterest: [
            { id: 'poi_26_1', name: 'Fragment Alpha', type: 'dungeon', discovered: false, description: 'The largest moon fragment. Its interior is a maze of half-rendered celestial architecture.' },
            { id: 'poi_26_2', name: 'The Crater Market', type: 'vendor', discovered: false, description: 'Vendors set up shop in impact craters. Unique celestial goods available nowhere else.' },
        ],
    },
    {
        id: 27, name: 'Data Sea', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 4,
        activeEvents: [], terrain: 'aquatic', weather: 'rain',
        description: 'An ocean of liquid information. The Ironborn have built platforms and rigs across its surface to mine raw data from the deep.',
        resources: ['Raw Data', 'Sea Metal', 'Deep Code'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [22, 26, 28, 40],
        pointsOfInterest: [
            { id: 'poi_27_1', name: 'Platform Seven', type: 'settlement', discovered: false, description: 'A data-mining rig turned permanent settlement. Rough but resilient.' },
        ],
    },
    {
        id: 28, name: 'Ethereal Gate', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 5,
        activeEvents: [], terrain: 'mountain', weather: 'fog',
        description: 'A massive gateway carved into a mountainside. It leads somewhere, but the destination changes every cycle. The Ironborn guard it jealously.',
        resources: ['Gate Stone', 'Ethereal Thread'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [23, 27, 29, 41],
        pointsOfInterest: [
            { id: 'poi_28_1', name: 'The Gate Itself', type: 'anomaly', discovered: false, description: 'Step through and arrive... somewhere. Rarely the same place twice. Always worth the journey.' },
        ],
    },
    {
        id: 29, name: 'The Lost Archives', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 6,
        activeEvents: [], terrain: 'underground', weather: 'clear',
        description: 'A vast underground library of physical data storage. Shelves stretch beyond sight. The Ironborn protect these records as a matter of honor.',
        resources: ['Archive Scrolls', 'Ancient Data'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [24, 28, 30, 42],
        pointsOfInterest: [
            { id: 'poi_29_1', name: 'The Forbidden Wing', type: 'dungeon', discovered: false, description: 'Sealed millennia ago. Whatever is stored here was deemed too dangerous to access.' },
            { id: 'poi_29_2', name: 'The Librarian', type: 'vendor', discovered: false, description: 'An ancient NPC who trades information for information. Never accepts material payment.' },
        ],
    },
    {
        id: 30, name: 'Inferno Ridge', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 7,
        activeEvents: [], terrain: 'mountain', weather: 'storm',
        description: 'A volcanic ridge where superheated code erupts from fissures. The Ironborn forge their greatest weapons in its heat. Few can withstand the temperatures.',
        resources: ['Magma Core', 'Forged Alloy', 'Fire Crystal'],
        npcsPresent: ['IRON_HAND'],
        discovered: false, adjacentSectors: [25, 29, 43],
        pointsOfInterest: [
            { id: 'poi_30_1', name: 'The Great Forge', type: 'landmark', discovered: false, description: 'The Ironborn\'s greatest forge. Weapons crafted here are legendar.' },
            { id: 'poi_30_2', name: 'Eruption Point', type: 'dungeon', discovered: false, description: 'The most active fissure. Incredibly dangerous but rich in rare materials.' },
        ],
    },

    // ════════════════════════════════════════
    // SECTORS 31-40: MIXED CONTESTED ZONES
    // ════════════════════════════════════════
    {
        id: 31, name: 'Glacier Point', controlledBy: null, threatLevel: 5,
        activeEvents: ['Territorial Dispute'],
        terrain: 'mountain', weather: 'storm',
        description: 'A frozen precipice where three faction territories converge. Ice covers everything. Skirmishes are constant and the ground is stained with data-blood.',
        resources: ['Frozen Core', 'Ice Crystal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [6, 10, 32, 36, 41],
        pointsOfInterest: [
            { id: 'poi_31_1', name: 'The Three-Way Bridge', type: 'landmark', discovered: false, description: 'A bridge where all three factions erected flags. None have been taken down. None ever will be.' },
            { id: 'poi_31_2', name: 'Ice Caverns', type: 'dungeon', discovered: false, description: 'Natural formations beneath the glacier. Rumored to contain pre-faction relics.' },
        ],
    },
    {
        id: 32, name: 'The Verdant Hub', controlledBy: null, threatLevel: 3,
        activeEvents: [],
        terrain: 'forest', weather: 'rain',
        description: 'A neutral zone by ancient agreement. Lush vegetation shelters a multicultural market. All factions trade here under a fragile truce.',
        resources: ['Trade Goods', 'Verdant Seeds', 'Spore Components'],
        npcsPresent: ['EMBER_WITCH', 'NULL_BYTE'],
        discovered: false, adjacentSectors: [11, 31, 33, 37],
        pointsOfInterest: [
            { id: 'poi_32_1', name: 'The Truce Market', type: 'vendor', discovered: false, description: 'The largest neutral trading post on The Grid. Violence here results in permanent exile.' },
            { id: 'poi_32_2', name: 'The Peace Tree', type: 'landmark', discovered: false, description: 'An enormous tree where the original truce was signed. Its bark records every agreement ever made.' },
        ],
    },
    {
        id: 33, name: 'Storm Watch', controlledBy: null, threatLevel: 6,
        activeEvents: ['Anomalous Weather'],
        terrain: 'wasteland', weather: 'storm',
        description: 'A weather monitoring station turned warzone. Perpetual storms ravage the landscape. All three factions want control of the weather array.',
        resources: ['Storm Data', 'Charged Fragments'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [16, 32, 34, 38],
        pointsOfInterest: [
            { id: 'poi_33_1', name: 'Weather Array Control', type: 'dungeon', discovered: false, description: 'Whoever controls this facility controls the weather in five adjacent sectors.' },
            { id: 'poi_33_2', name: 'The Eye', type: 'anomaly', discovered: false, description: 'The calm center of the permanent storm. Unsettlingly peaceful.' },
        ],
    },
    {
        id: 34, name: 'Apex Node', controlledBy: null, threatLevel: 5,
        activeEvents: [],
        terrain: 'urban', weather: 'clear',
        description: 'The highest point of The Grid\'s network architecture. Data flows downhill from here. All factions consider it strategically vital.',
        resources: ['Apex Data', 'Premium Circuits'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [17, 33, 35, 39],
        pointsOfInterest: [
            { id: 'poi_34_1', name: 'The Pinnacle', type: 'landmark', discovered: false, description: 'The absolute peak. Stand here and every transmitted message on The Grid passes through you.' },
        ],
    },
    {
        id: 35, name: 'The Silent Grove', controlledBy: null, threatLevel: 4,
        activeEvents: [],
        terrain: 'forest', weather: 'fog',
        description: 'A forest where no sound propagates. Communication requires light signals or written messages. The silence is oppressive and absolute.',
        resources: ['Silent Wood', 'Mute Crystal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [18, 34, 36, 40],
        pointsOfInterest: [
            { id: 'poi_35_1', name: 'The Listening Stone', type: 'anomaly', discovered: false, description: 'The only point where sound works. It amplifies whispers to thunderous volume.' },
            { id: 'poi_35_2', name: 'Silent Hermit', type: 'settlement', discovered: false, description: 'A lone Architect who has lived here for decades. Communicates only through gestures.' },
        ],
    },
    {
        id: 36, name: 'Nova Prime', controlledBy: 'TECHNOCRATS', threatLevel: 6,
        activeEvents: ['Power Surge'],
        terrain: 'urban', weather: 'anomaly',
        description: 'A sector experiencing a continuous energy nova. The Technocrats attempt to harness it. The Ironborn want to weaponize it. The Keepers want to study it.',
        resources: ['Nova Energy', 'Supercharged Cells'],
        npcsPresent: ['CIPHER_ZERO'],
        discovered: false, adjacentSectors: [19, 31, 35, 41],
        pointsOfInterest: [
            { id: 'poi_36_1', name: 'The Nova Core', type: 'anomaly', discovered: false, description: 'The epicenter of the energy nova. Radiation levels are lethal. Rewards are unmatched.' },
            { id: 'poi_36_2', name: 'Hazmat Vendor', type: 'vendor', discovered: false, description: 'Sells protective equipment for exploring high-radiation zones. Overpriced but essential.' },
        ],
    },
    {
        id: 37, name: 'The Brass City', controlledBy: 'IRONBORN_COLLECTIVE', threatLevel: 5,
        activeEvents: [],
        terrain: 'urban', weather: 'clear',
        description: 'An Ironborn city built entirely from brass and bronze. Gears turn constantly, powering ancient clockwork mechanisms. Steam rises from every surface.',
        resources: ['Brass Gears', 'Clockwork Parts', 'Steam Cells'],
        npcsPresent: ['RUST_PROPHET'],
        discovered: false, adjacentSectors: [20, 32, 38, 42],
        pointsOfInterest: [
            { id: 'poi_37_1', name: 'The Grand Clocktower', type: 'landmark', discovered: false, description: 'The city\'s heart. Its ticking is heard across three sectors. Some say it counts down to something.' },
            { id: 'poi_37_2', name: 'Gearwright Guild', type: 'vendor', discovered: false, description: 'Master craftspeople who build anything mechanical. Custom orders welcome.' },
        ],
    },
    {
        id: 38, name: 'Circuit Breaker', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 5,
        activeEvents: [],
        terrain: 'ruins', weather: 'rain',
        description: 'The site of a catastrophic system failure. Burnt-out circuits the size of buildings litter the landscape. The Keepers study the patterns in the destruction.',
        resources: ['Burnt Circuit', 'Failure Data', 'Salvage Parts'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [21, 33, 37, 39, 43],
        pointsOfInterest: [
            { id: 'poi_38_1', name: 'Ground Zero', type: 'landmark', discovered: false, description: 'The exact point of the original failure. A crater that still sparks occasionally.' },
            { id: 'poi_38_2', name: 'The Pattern Study', type: 'anomaly', discovered: false, description: 'A Keeper research site. They believe the failure was deliberate and seek its meaning.' },
        ],
    },
    {
        id: 39, name: 'The Deep Web', controlledBy: 'TECHNOCRATS', threatLevel: 7,
        activeEvents: ['Encryption Lockdown'],
        terrain: 'underground', weather: 'clear',
        description: 'The deepest layer of The Grid accessible without root permissions. Encrypted tunnels twist and branch endlessly. Get lost and you might never be found.',
        resources: ['Encrypted Data', 'Deep Thread', 'Root Keys'],
        npcsPresent: ['GHOST_SIGNAL'],
        discovered: false, adjacentSectors: [26, 34, 38, 40, 44],
        pointsOfInterest: [
            { id: 'poi_39_1', name: 'Layer 7 Access Point', type: 'dungeon', discovered: false, description: 'The entrance to the seventh encryption layer. Each layer is exponentially harder to crack.' },
            { id: 'poi_39_2', name: 'The Black Market', type: 'vendor', discovered: false, description: 'If it exists on The Grid, it can be bought here. No questions asked. No receipts given.' },
        ],
    },
    {
        id: 40, name: 'Helios Core', controlledBy: 'KEEPERS_OF_THE_VEIL', threatLevel: 6,
        activeEvents: [],
        terrain: 'void', weather: 'anomaly',
        description: 'A miniature star burns at this sector\'s center. The Keepers worship it as a manifestation of pure computational energy. Its warmth sustains surrounding sectors.',
        resources: ['Solar Essence', 'Helios Crystal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [27, 35, 39, 45],
        pointsOfInterest: [
            { id: 'poi_40_1', name: 'The Sun Temple', type: 'landmark', discovered: false, description: 'A Keeper temple orbiting the miniature star. Its priests maintain the energy balance.' },
            { id: 'poi_40_2', name: 'Solar Collector', type: 'dungeon', discovered: false, description: 'Get close enough to the star to harvest its energy. Getting too close is fatal.' },
        ],
    },

    // ════════════════════════════════════════
    // SECTORS 41-50: HIGH-THREAT FRONTIER ZONES
    // ════════════════════════════════════════
    {
        id: 41, name: 'The Phantom Array', controlledBy: null, threatLevel: 7,
        activeEvents: ['Ghost Signals Detected'],
        terrain: 'void', weather: 'anomaly',
        description: 'An array of structures that flicker in and out of existence. They are there when you look, gone when you approach. The frontier begins here.',
        resources: ['Phantom Alloy', 'Phase Crystal'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [28, 31, 36, 42, 46],
        pointsOfInterest: [
            { id: 'poi_41_1', name: 'The Phantom Spire', type: 'anomaly', discovered: false, description: 'The tallest phantom structure. It appears for exactly 47 seconds every hour.' },
            { id: 'poi_41_2', name: 'Phase Walker Camp', type: 'settlement', discovered: false, description: 'Frontier explorers who have learned to navigate the phantom shifts. Rough but welcoming.' },
        ],
    },
    {
        id: 42, name: 'Obsidian Wastes', controlledBy: null, threatLevel: 8,
        activeEvents: [],
        terrain: 'wasteland', weather: 'sandstorm',
        description: 'Miles of black glass stretching to every horizon. The ground reflects the sky, creating a disorienting mirror effect. Navigation tools fail here.',
        resources: ['Obsidian Shards', 'Mirror Dust', 'Black Glass'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [29, 37, 41, 43, 47],
        pointsOfInterest: [
            { id: 'poi_42_1', name: 'The Mirror Labyrinth', type: 'dungeon', discovered: false, description: 'A maze of reflective obsidian. Your reflections move independently. Some are hostile.' },
        ],
    },
    {
        id: 43, name: 'Alpha Site', controlledBy: null, threatLevel: 8,
        activeEvents: ['Frontier Expansion'],
        terrain: 'ruins', weather: 'fog',
        description: 'The legendary first settlement on The Grid. Now ruins, but still radiating foundational energy. Every faction claims it as their birthplace.',
        resources: ['Foundation Code', 'Primal Data', 'Ancient Alloy'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [30, 38, 42, 44, 48],
        pointsOfInterest: [
            { id: 'poi_43_1', name: 'The First Terminal', type: 'landmark', discovered: false, description: 'The very first input terminal ever placed on The Grid. It still accepts commands. What they do is unknown.' },
            { id: 'poi_43_2', name: 'Ruin Delvers Guild', type: 'vendor', discovered: false, description: 'Specialists in frontier salvage. They know where to find things thought lost forever.' },
            { id: 'poi_43_3', name: 'The Foundation Stone', type: 'anomaly', discovered: false, description: 'A stone that predates The Grid itself. How is that possible? No one knows.' },
        ],
    },
    {
        id: 44, name: 'Omega Point', controlledBy: null, threatLevel: 9,
        activeEvents: ['Reality Distortion'],
        terrain: 'void', weather: 'anomaly',
        description: 'The theoretical end of The Grid. Beyond here, nothing has been rendered. Reality frays at the edges. Those who venture too far do not return as themselves.',
        resources: ['Omega Fragment', 'End-Code'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [39, 43, 45, 49],
        pointsOfInterest: [
            { id: 'poi_44_1', name: 'The Edge', type: 'anomaly', discovered: false, description: 'The literal boundary of existence. Stare into the void beyond and it stares back. It also waves.' },
            { id: 'poi_44_2', name: 'The Last Outpost', type: 'settlement', discovered: false, description: 'A tiny station manned by a single Architect who has been here since the beginning. They seem... different.' },
        ],
    },
    {
        id: 45, name: 'The Crimson Rift', controlledBy: null, threatLevel: 8,
        activeEvents: ['Rift Expansion'],
        terrain: 'void', weather: 'storm',
        description: 'A bleeding tear in The Grid that pulses red. Something on the other side pushes against the barrier. The factions debate whether to seal it or open it.',
        resources: ['Rift Blood', 'Crimson Shard'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [40, 44, 46, 50],
        pointsOfInterest: [
            { id: 'poi_45_1', name: 'The Bleeding Edge', type: 'anomaly', discovered: false, description: 'The rift\'s widest point. Stand here and you can hear something breathing on the other side.' },
            { id: 'poi_45_2', name: 'Rift Watcher Garrison', type: 'settlement', discovered: false, description: 'A joint-faction garrison whose sole purpose is monitoring the rift. They take their job very seriously.' },
        ],
    },
    {
        id: 46, name: 'Starfall Basin', controlledBy: null, threatLevel: 7,
        activeEvents: [],
        terrain: 'wasteland', weather: 'clear',
        description: 'A crater field from a celestial bombardment. Strange minerals glow in the impact sites. The stars that fell here were not natural.',
        resources: ['Star Metal', 'Impact Crystal', 'Celestial Dust'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [41, 45, 47],
        pointsOfInterest: [
            { id: 'poi_46_1', name: 'Impact Site Zero', type: 'dungeon', discovered: false, description: 'The deepest crater. Something at the bottom is emitting a signal. It has been for centuries.' },
            { id: 'poi_46_2', name: 'Star Metal Forge', type: 'vendor', discovered: false, description: 'A legendary forge that works with celestial metals. Produces weapons of extraordinary power.' },
        ],
    },
    {
        id: 47, name: 'The Iron Tundra', controlledBy: null, threatLevel: 8,
        activeEvents: ['Extreme Cold'],
        terrain: 'wasteland', weather: 'storm',
        description: 'A frozen expanse of iron-rich permafrost. Temperatures crash power systems. Only the most prepared Architects venture this far into the frontier.',
        resources: ['Cryo-Iron', 'Frozen Data', 'Tundra Moss'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [42, 46, 48],
        pointsOfInterest: [
            { id: 'poi_47_1', name: 'The Frozen Server', type: 'dungeon', discovered: false, description: 'An ancient server farm preserved perfectly by the cold. Its data has been frozen mid-process for eons.' },
        ],
    },
    {
        id: 48, name: 'Neon Drift', controlledBy: null, threatLevel: 9,
        activeEvents: ['Spatial Anomaly'],
        terrain: 'urban', weather: 'anomaly',
        description: 'A city that drifts through The Grid on no fixed path. Finding it is hard. Leaving it is harder. Its neon streets shift underfoot like a dream.',
        resources: ['Drift Crystal', 'Neon Essence', 'Unstable Alloy'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [43, 47, 49],
        pointsOfInterest: [
            { id: 'poi_48_1', name: 'The Shifting Streets', type: 'anomaly', discovered: false, description: 'Streets that rearrange themselves. Maps are useless. Instinct is everything.' },
            { id: 'poi_48_2', name: 'The Drifter\'s Bar', type: 'settlement', discovered: false, description: 'A bar that serves drinks made of compressed data. The stories here are worth the trip.' },
            { id: 'poi_48_3', name: 'Neon Merchant', type: 'vendor', discovered: false, description: 'Sells goods that only exist while the city is nearby. Use them quickly.' },
        ],
    },
    {
        id: 49, name: 'The Final Gateway', controlledBy: null, threatLevel: 9,
        activeEvents: ['Dimensional Instability'],
        terrain: 'void', weather: 'anomaly',
        description: 'A gate to somewhere else entirely. Not another sector — another Grid. Another Construct. The implications are staggering and terrifying.',
        resources: ['Gateway Fragment', 'Trans-Dimensional Alloy'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [44, 48, 50],
        pointsOfInterest: [
            { id: 'poi_49_1', name: 'The Other Side', type: 'anomaly', discovered: false, description: 'Glimpse through the gateway and see a world almost like this one. But wrong. Subtly, horribly wrong.' },
            { id: 'poi_49_2', name: 'Gateway Research Station', type: 'settlement', discovered: false, description: 'Scientists from all factions study the gateway together. It is the one thing they agree on.' },
        ],
    },
    {
        id: 50, name: 'Terminus', controlledBy: null, threatLevel: 10,
        activeEvents: ['The Final Signal'],
        terrain: 'void', weather: 'anomaly',
        description: 'The end of everything. The last sector. Beyond this, there is nothing — not void, not space, not even the absence of something. Just... end.',
        resources: ['End-Code', 'Terminal Fragment', 'Omega Data'],
        npcsPresent: [],
        discovered: false, adjacentSectors: [45, 49],
        pointsOfInterest: [
            { id: 'poi_50_1', name: 'The Last Pixel', type: 'landmark', discovered: false, description: 'The final rendered point of The Grid. Touch it and feel the weight of everything that exists behind you.' },
            { id: 'poi_50_2', name: 'The Terminal', type: 'anomaly', discovered: false, description: 'A single terminal sitting at the end of all things. It has a blinking cursor. It waits for input. What would you type?' },
        ],
    },
];
