import type { Equipment } from '@/types';

export const STARTER_EQUIPMENT: Equipment[] = [
    {
        id: 'starter_weapon',
        name: 'Standard Issue Sidearm',
        slot: 'WEAPON',
        rarity: 'COMMON',
        description: 'A reliable if unremarkable energy pistol. Every Architect gets one.',
        stats: { COMBAT: 2 },
        lore: 'Mass-produced in Sector S-3. Serial number filed off.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
    {
        id: 'starter_armor',
        name: 'Threadbare Field Coat',
        slot: 'ARMOR',
        rarity: 'COMMON',
        description: 'A battered coat lined with thin carbon fiber weave. Better than nothing.',
        stats: { SURVIVAL: 2 },
        lore: 'Issued to all new operatives. The stains are from the previous owner.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
    {
        id: 'starter_accessory',
        name: 'Cracked Data Monocle',
        slot: 'ACCESSORY',
        rarity: 'COMMON',
        description: 'A heads-up display with a hairline fracture across the lens.',
        stats: { HACKING: 2 },
        lore: 'Salvaged from a decommissioned recon unit. The crack adds character.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
    {
        id: 'starter_companion',
        name: 'Glitched Drone v0.1',
        slot: 'COMPANION',
        rarity: 'COMMON',
        description: 'A small hovering drone that occasionally sparks and reboots mid-flight.',
        stats: { ENGINEERING: 2 },
        lore: 'Built from spare parts in the depot. It follows you because it has nowhere else to go.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
    {
        id: 'starter_implant',
        name: 'Basic Neural Thread',
        slot: 'IMPLANT',
        rarity: 'COMMON',
        description: 'A crude neural interface that links your thoughts to the Grid.',
        stats: { ARCANA: 2 },
        lore: 'Street-grade wetware. Installation was painful but you survived. Mostly.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
    {
        id: 'starter_relic',
        name: 'Tarnished Faction Sigil',
        slot: 'RELIC',
        rarity: 'COMMON',
        description: 'A small metallic emblem bearing your faction\'s mark. Slightly warm to the touch.',
        stats: { DIPLOMACY: 2 },
        lore: 'Given to every initiate during the oath ceremony. Some say it hums in the presence of allies.',
        acquiredAt: new Date().toISOString(),
        source: 'Initialization Protocol',
    },
];
